name: checkout-pr

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  checkout-pr:
    name: default-pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - run: git status
    - run: cat info.txt
  checkout2-pr:
    name: head-pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false
    - run: git status
    - run: cat info.txt
